<table class="ee-notebook-buttons" align="left"><td>
<a target="_blank"  href="http://colab.research.google.com/github/google/earthengine-community/blob/master/guides/linked/ee-api-colab-setup.ipynb">
    <img src="https://www.tensorflow.org/images/colab_logo_32px.png" /> Run in Google Colab</a>
</td><td>
<a target="_blank"  href="https://github.com/google/earthengine-community/blob/master/guides/linked/ee-api-colab-setup.ipynb"><img width=32px src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" /> View source on GitHub</a></td></table>

# Earth Engine Python API Colab Setup

This notebook demonstrates how to setup the Earth Engine Python API in Colab and provides several examples of how to print and visualize Earth Engine processed data.

## Import API and get credentials

The Earth Engine API is installed by default in Google Colaboratory so requires only importing and authenticating. These steps must be completed for each new Colab session, if you restart your Colab kernel, or if your Colab virtual machine is recycled due to inactivity.

### Import the API

Run the following cell to import the API into your session.

In [ ]:
import ee
import pandas as pd
import openpyxl
import ee
import datetime
import os
from PIL import Image
import numpy as np
import json
import IPython.display as disp
import csv

### Authenticate and initialize

Run the `ee.Authenticate` function to authenticate your access to Earth Engine servers and `ee.Initialize` to initialize it. Upon running the following cell you'll be asked to grant Earth Engine access to your Google account. Follow the instructions printed to the cell.

In [ ]:
# Trigger the authentication flow.
ee.Authenticate()

# Initialize the library.
ee.Initialize(project="ee-cima")
print(ee.String('Hello from the Earth Engine servers!').getInfo())

Hello from the Earth Engine servers!

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:

! cp "/content/drive/Othercomputers/MiPC/Code_OilSpill/Apis/EEAPI/s1_ard.py"  "/content/"
! cp "/content/drive/Othercomputers/MiPC/Code_OilSpill/Apis/EEAPI/terrain_flattening.py"  "/content/"
! cp "/content/drive/Othercomputers/MiPC/Code_OilSpill/Apis/EEAPI/helper.py"  "/content/"
! cp "/content/drive/Othercomputers/MiPC/Code_OilSpill/Apis/EEAPI/speckle_filter.py"  "/content/"
! cp "/content/drive/Othercomputers/MiPC/Code_OilSpill/Apis/EEAPI/border_noise_correction.py"  "/content/"
! cp "/content/drive/Othercomputers/MiPC/Code_OilSpill/Apis/EEAPI/wrapper.py"  "/content/"
! cp "/content/drive/Othercomputers/MiPC/Code_OilSpill/Apis/oefa_cde_img_result3.csv"  "/content/"
! cp "/content/drive/Othercomputers/MiPC/Code_OilSpill/Apis/oefa_cde_img_result3_fullvalues.xlsx"  "/content/"
! cp "/content/drive/Othercomputers/MiPC/Code_OilSpill/Apis/last_dance/LastImages_256_osinergmin.xlsx"  "/content/"

In [ ]:
df = pd.read_excel('/content/LastImages_256_osinergmin.xlsx')

In [ ]:
df.columns

Index(['Unnamed: 0.1', 'Original index', 'ID', 'Date and Time', 'Platform',
       'Instruments', 'Product Type', 'Polarizations', 'Coordinates',
       'Asset Link', 'Asset Type', 'Unnamed: 0', '...1', 'Nro', 'AÑO', 'Fecha',
       'Locación', 'Empresa', 'VOLUMEN', 'EXTENSIÓN', 'Tipo de Producto',
       'departamento', 'ciudad', 'datetime', 'bbox', 'coordinates', 'LON',
       'LAT', 'geometry', 'bbox_converted'],
      dtype='object')

## Test the API

Coordenadas formato json **ee**


**SAVE FILES GOOGLE DRIVE**

In [ ]:
import sys
import os
import wrapper as wp

In [ ]:
from IPython.display import Image
import pandas as pd
from datetime import timedelta

In [ ]:
def data_str(df):
    id = df["Original index"]
    return id

In [ ]:
data_str(df)

0     10
1     11
2     13
3     13
4     14
5     14
6     14
7     15
8     15
9     16
10    17
11    17
12    18
13    19
14    21
15    22
16    23
17    24
18    25
Name: Original index, dtype: int64

In [ ]:
df.head()

,Unnamed: 0.1,Original index,ID,Date and Time,Platform,Instruments,Product Type,Polarizations,Coordinates,Asset Link,...,Tipo de Producto,departamento,ciudad,datetime,bbox,coordinates,LON,LAT,geometry,bbox_converted
0,0,10,S1A_IW_GRDH_1SSV_20150527T234306_20150527T2343...,2015-05-27 23:43:06,sentinel-1a,c-sar,GRD,VV,"[[[-81.04514081754914, -8.400250866996764], [-...",s3://EODATA/Sentinel-1/SAR/IW_GRDH_1S-COG/2015...,...,NO SE DETERMINÓ,LAMBAYEQUE,ETEN,2015-05-21T00:00:00Z/2015-06-03T23:59:59Z,"[-80.1899209999998, -6.9041417, -79.9499209999...","('-6.7841417', '-79.844921')",-6.784142,-79.844921,POINT (-79.844921 -6.7841417),"[[[-79.94992099999979, -6.9041417], [-79.94992..."
1,1,11,S1A_IW_GRDH_1SSV_20160215T234301_20160215T2343...,2016-02-15 23:43:01,sentinel-1a,c-sar,GRD,VV,"[[[-80.98076824367735, -8.689397503181628], [-...",s3://EODATA/Sentinel-1/SAR/IW_GRDH_1S-COG/2016...,...,NO SE DETERMINÓ,LA LIBERTAD,TRUJILLO,2016-02-13T00:00:00Z/2016-02-26T23:59:59Z,"[-79.31877419999985, -8.2316778, -79.078774199...","('-8.1116778', '-79.0287742')",-8.111678,-79.028774,POINT (-79.0287742 -8.1116778),"[[[-79.07877419999984, -8.2316778], [-79.07877..."
2,2,13,S1B_IW_GRDH_1SDV_20170721T234317_20170721T2343...,2017-07-21 23:43:17,sentinel-1b,c-sar,GRD,"VV, VH","[[[-81.56496800825946, -6.050980963469723], [-...",s3://EODATA/Sentinel-1/SAR/IW_GRDH_1S-COG/2017...,...,Petróleo,Piura,Talara,2017-07-11T00:00:00Z/2017-07-24T23:59:59Z,"[-81.5018334999999, -4.6996872000000005, -81.2...","('-4.5796872', '-81.2718335')",-4.579687,-81.271833,POINT (-81.2718335 -4.5796872),"[[[-81.2618334999999, -4.6996872000000005], [-..."
3,3,13,S1B_IW_GRDH_1SDV_20170718T110114_20170718T1101...,2017-07-18 11:01:14,sentinel-1b,c-sar,GRD,"VV, VH","[[[-79.29050523752547, -4.462938844796035], [-...",s3://EODATA/Sentinel-1/SAR/IW_GRDH_1S-COG/2017...,...,Petróleo,Piura,Talara,2017-07-11T00:00:00Z/2017-07-24T23:59:59Z,"[-81.5018334999999, -4.6996872000000005, -81.2...","('-4.5796872', '-81.2718335')",-4.579687,-81.271833,POINT (-81.2718335 -4.5796872),"[[[-81.2618334999999, -4.6996872000000005], [-..."
4,4,14,S1B_IW_GRDH_1SDV_20180410T104648_20180410T1047...,2018-04-10 10:46:48,sentinel-1b,c-sar,GRD,"VV, VH","[[[-76.78273212917428, -11.71504526188707], [-...",s3://EODATA/Sentinel-1/SAR/IW_GRDH_1S-COG/2018...,...,Aceite básico,LIMA,CALLAO,2018-04-01T00:00:00Z/2018-04-14T23:59:59Z,"[-77.37222979999993, -11.9487168, -77.13222979...","('-11.8287168', '-77.1622298')",-11.828717,-77.162230,POINT (-77.1622298 -11.8287168),"[[[-77.13222979999992, -11.9487168], [-77.1322..."

In [ ]:
invalid_rows = df[df['Date and Time'].isna()]

# Print the problematic rows
if not invalid_rows.empty:
    print("Rows with invalid or missing dates:")
    print(invalid_rows[['Date and Time', 'bbox_converted']])

# Iterate through rows and process valid dates
for index, row in df.iterrows():
    # Check if the date is valid
    if pd.isna(row['Date and Time']):
        print(f"Skipping row {index} due to invalid date.")
        continue

    try:
        start_date = pd.to_datetime(row['Date and Time'])
        end_date = start_date + timedelta(days=8)
        print(f"Start date: {start_date.strftime('%Y-%m-%d')}")
        print(f"End date: {end_date.strftime('%Y-%m-%d')}")

        # Load coordinates if they exist
        if isinstance(row['bbox_converted'], str):
            coordinates = json.loads(row['bbox_converted'])
            polygon = ee.Geometry.Polygon(coordinates)
            print(f"Polygon info: {polygon.getInfo()}")
        else:
            print(f"Invalid or missing bbox data in row {index}.")

    except Exception as e:
        print(f"Error processing row {index}: {e}")

Start date: 2015-05-27
End date: 2015-06-04
Polygon info: {'type': 'Polygon', 'coordinates': [[[-80.1899209999998, -6.9041417], [-79.94992099999979, -6.9041417], [-79.94992099999979, -6.6641417], [-80.1899209999998, -6.6641417], [-80.1899209999998, -6.9041417]]]}
Start date: 2016-02-15
End date: 2016-02-23
Polygon info: {'type': 'Polygon', 'coordinates': [[[-79.31877419999985, -8.2316778], [-79.07877419999984, -8.2316778], [-79.07877419999984, -7.991677800000001], [-79.31877419999985, -7.991677800000001], [-79.31877419999985, -8.2316778]]]}
Start date: 2017-07-21
End date: 2017-07-29
Polygon info: {'type': 'Polygon', 'coordinates': [[[-81.5018334999999, -4.6996872000000005], [-81.2618334999999, -4.6996872000000005], [-81.2618334999999, -4.4596872], [-81.5018334999999, -4.4596872], [-81.5018334999999, -4.6996872000000005]]]}
Start date: 2017-07-18
End date: 2017-07-26
Polygon info: {'type': 'Polygon', 'coordinates': [[[-81.5018334999999, -4.6996872000000005], [-81.2618334999999, -4.6996872000000005], [-81.2618334999999, -4.4596872], [-81.5018334999999, -4.4596872], [-81.5018334999999, -4.6996872000000005]]]}
Start date: 2018-04-10
End date: 2018-04-18
Polygon info: {'type': 'Polygon', 'coordinates': [[[-77.37222979999993, -11.9487168], [-77.13222979999992, -11.9487168], [-77.13222979999992, -11.708716800000001], [-77.37222979999993, -11.708716800000001], [-77.37222979999993, -11.9487168]]]}
Start date: 2018-04-06
End date: 2018-04-14
Polygon info: {'type': 'Polygon', 'coordinates': [[[-77.37222979999993, -11.9487168], [-77.13222979999992, -11.9487168], [-77.13222979999992, -11.708716800000001], [-77.37222979999993, -11.708716800000001], [-77.37222979999993, -11.9487168]]]}
Start date: 2018-04-05
End date: 2018-04-13
Polygon info: {'type': 'Polygon', 'coordinates': [[[-77.37222979999993, -11.9487168], [-77.13222979999992, -11.9487168], [-77.13222979999992, -11.708716800000001], [-77.37222979999993, -11.708716800000001], [-77.37222979999993, -11.9487168]]]}
Start date: 2018-10-08
End date: 2018-10-16
Polygon info: {'type': 'Polygon', 'coordinates': [[[-81.5018334999999, -4.6996872000000005], [-81.2618334999999, -4.6996872000000005], [-81.2618334999999, -4.4596872], [-81.5018334999999, -4.4596872], [-81.5018334999999, -4.6996872000000005]]]}
Start date: 2018-09-26
End date: 2018-10-04
Polygon info: {'type': 'Polygon', 'coordinates': [[[-81.5018334999999, -4.6996872000000005], [-81.2618334999999, -4.6996872000000005], [-81.2618334999999, -4.4596872], [-81.5018334999999, -4.4596872], [-81.5018334999999, -4.6996872000000005]]]}
Start date: 2018-11-29
End date: 2018-12-07
Polygon info: {'type': 'Polygon', 'coordinates': [[[-79.31877419999985, -8.2316778], [-79.07877419999984, -8.2316778], [-79.07877419999984, -7.991677800000001], [-79.31877419999985, -7.991677800000001], [-79.31877419999985, -8.2316778]]]}
Start date: 2020-03-31
End date: 2020-04-08
Polygon info: {'type': 'Polygon', 'coordinates': [[[-81.5018334999999, -4.6996872000000005], [-81.2618334999999, -4.6996872000000005], [-81.2618334999999, -4.4596872], [-81.5018334999999, -4.4596872], [-81.5018334999999, -4.6996872000000005]]]}
Start date: 2020-03-19
End date: 2020-03-27
Polygon info: {'type': 'Polygon', 'coordinates': [[[-81.5018334999999, -4.6996872000000005], [-81.2618334999999, -4.6996872000000005], [-81.2618334999999, -4.4596872], [-81.5018334999999, -4.4596872], [-81.5018334999999, -4.6996872000000005]]]}
Start date: 2021-01-25
End date: 2021-02-02
Polygon info: {'type': 'Polygon', 'coordinates': [[[-81.5018334999999, -4.6996872000000005], [-81.2618334999999, -4.6996872000000005], [-81.2618334999999, -4.4596872], [-81.5018334999999, -4.4596872], [-81.5018334999999, -4.6996872000000005]]]}
Start date: 2022-01-25
End date: 2022-02-02
Polygon info: {'type': 'Polygon', 'coordinates': [[[-77.37222979999993, -11.9487168], [-77.13222979999992, -11.9487168], [-77.13222979999992, -11.708716800000001], [-77.37222979999993, -11.708716800000001], [-77.37222979999993, -11.9487168]]]}
Start date: 2022-08-18
End date: 2022-08-26
Polygon info: {'type': 'Polygon', 'coordinates': [[[-81.5018334999999, -4.6996872000000005], [-81.2618334999999, -4.6996872000000005], [-81.2618334999999, -4.4596872], [-81.5018334999999, -4.4596872], [-81.5018334999999, -4.6996872000000005]]]}
Start date: 2022-10-17
End date: 2022-10-25
Polygon info: {'type': 'Polygon', 'coordinates': [[[-81.5018334999999, -4.6996872000000005], [-81.2618334999999, -4.6996872000000005], [-81.2618334999999, -4.4596872], [-81.5018334999999, -4.4596872], [-81.5018334999999, -4.6996872000000005]]]}
Start date: 2022-01-25
End date: 2022-02-02
Polygon info: {'type': 'Polygon', 'coordinates': [[[-77.38088499999994, -11.921154], [-77.14088499999993, -11.921154], [-77.14088499999993, -11.681154000000001], [-77.38088499999994, -11.681154000000001], [-77.38088499999994, -11.921154]]]}
Start date: 2022-01-25
End date: 2022-02-02
Polygon info: {'type': 'Polygon', 'coordinates': [[[-77.37133599999996, -11.958696], [-77.13133599999995, -11.958696], [-77.13133599999995, -11.718696000000001], [-77.37133599999996, -11.718696000000001], [-77.37133599999996, -11.958696]]]}
Start date: 2022-01-25
End date: 2022-02-02
Polygon info: {'type': 'Polygon', 'coordinates': [[[-77.33610200000001, -12.149534], [-77.096102, -12.149534], [-77.096102, -11.909534], [-77.33610200000001, -11.909534], [-77.33610200000001, -12.149534]]]}

In [ ]:
log_entries = []
for index, row in df.iterrows():
    # Check and convert dates
    start_date = pd.to_datetime(row['Date and Time'], errors='coerce')
    if pd.isna(start_date):
        print(f"Invalid date for row {index}, skipping.")
        continue

    end_date = start_date + timedelta(days=8)

    # Define the ROI
    try:
        roi = ee.Geometry.Polygon(json.loads(row["bbox_converted"]))
    except Exception as e:
        print(f"Error converting bbox for row {index}: {e}")
        continue

    # Define parameter dictionary
    parameter = {
        'START_DATE': start_date.strftime('%Y-%m-%d'),
        'STOP_DATE': end_date.strftime('%Y-%m-%d'),
        'POLARIZATION': 'VV',
        'ROI': roi,
        'APPLY_BORDER_NOISE_CORRECTION': False,
        'APPLY_SPECKLE_FILTERING': True,
        'SPECKLE_FILTER_FRAMEWORK': 'MONO',
        'SPECKLE_FILTER': 'LEE',
        'SPECKLE_FILTER_KERNEL_SIZE': 7,
        'SPECKLE_FILTER_NR_OF_IMAGES': 10,
        'APPLY_TERRAIN_FLATTENING': True,
        'DEM': ee.Image('USGS/SRTMGL1_003'),
        'TERRAIN_FLATTENING_MODEL': 'VOLUME',
        'TERRAIN_FLATTENING_ADDITIONAL_LAYOVER_SHADOW_BUFFER': 0,
        'FORMAT': 'DB',
        'CLIP_TO_ROI': True,
        'SAVE_ASSET': True
    }

    # Call the preprocessing function
    wp.s1_preproc(parameter, df["Original index"][index])

    log_entries.append({
        'file_name': f'{start_date.strftime("%Y%m%d")}_S1_GRD',
        'location': f'{row["bbox_converted"]}',
        'time': start_date.strftime('%Y-%m-%d')
    })
    print(f'Processed data for event on {start_date.strftime("%Y-%m-%d")}')

Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1A_IW_GRDH_1SSV_20150527T234306_20150527T234331_006113_007EFD_445A
Exporting 10_2015-05-27_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2015-05-27
Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1A_IW_GRDH_1SSV_20160215T234301_20160215T234330_009963_00EA32_E4EE
Exporting 11_2016-02-15_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2016-02-15
Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20170721T234317_20170721T234342_006592_00B988_A1D7
Exporting 13_2017-07-21_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2017-07-21
Number of images in collection:  2
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20170718T110114_20170718T110139_006541_00B809_7EEB
Exporting 13_2017-07-18_S1_GRD to oefa_img_v4_256_real
S1B_IW_GRDH_1SDV_20170721T234317_20170721T234342_006592_00B988_A1D7
Exporting 13_2017-07-21_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2017-07-18
Number of images in collection:  2
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20180410T104648_20180410T104705_010420_012FB5_CD87
Exporting 14_2018-04-10_S1_GRD to oefa_img_v4_256_real
S1B_IW_GRDH_1SDV_20180417T103835_20180417T103900_010522_0132F6_3EF4
Exporting 14_2018-04-17_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2018-04-10
Number of images in collection:  2
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20180406T233312_20180406T233341_010369_012E17_63A4
Exporting 14_2018-04-06_S1_GRD to oefa_img_v4_256_real
S1B_IW_GRDH_1SDV_20180410T104648_20180410T104705_010420_012FB5_CD87
Exporting 14_2018-04-10_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2018-04-06
Number of images in collection:  3
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20180405T103835_20180405T103900_010347_012D5F_F456
Exporting 14_2018-04-05_S1_GRD to oefa_img_v4_256_real
S1B_IW_GRDH_1SDV_20180406T233312_20180406T233341_010369_012E17_63A4
Exporting 14_2018-04-06_S1_GRD to oefa_img_v4_256_real
S1B_IW_GRDH_1SDV_20180410T104648_20180410T104705_010420_012FB5_CD87
Exporting 14_2018-04-10_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2018-04-05
Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20181008T234327_20181008T234352_013067_01824B_861F
Exporting 15_2018-10-08_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2018-10-08
Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20180926T234327_20180926T234352_012892_017CF5_2A08
Exporting 15_2018-09-26_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2018-09-26
Number of images in collection:  3
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20181129T105350_20181129T105415_013818_0199CB_E182
Exporting 16_2018-11-29_S1_GRD to oefa_img_v4_256_real
S1B_IW_GRDH_1SDV_20181129T105415_20181129T105441_013818_0199CB_30CF
Exporting 16_2018-11-29_S1_GRD to oefa_img_v4_256_real
S1B_IW_GRDH_1SDV_20181202T233423_20181202T233448_013869_019B6C_0942
Exporting 16_2018-12-02_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2018-11-29
Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20200331T234330_20200331T234355_020942_027B98_44C2
Exporting 17_2020-03-31_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2020-03-31
Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20200319T234330_20200319T234355_020767_027611_2D90
Exporting 17_2020-03-19_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2020-03-19
Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1B_IW_GRDH_1SDV_20210125T234337_20210125T234402_025317_0303E9_2A63
Exporting 18_2021-01-25_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2021-01-25
Number of images in collection:  2
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1A_IW_GRDH_1SDV_20220125T104728_20220125T104757_041616_04F352_C4A4
Exporting 19_2022-01-25_S1_GRD to oefa_img_v4_256_real
S1A_IW_GRDH_1SDV_20220125T104757_20220125T104819_041616_04F352_6EA6
Exporting 19_2022-01-25_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2022-01-25
Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1A_IW_GRDH_1SDV_20220818T234443_20220818T234508_044613_05534E_EAC9
Exporting 21_2022-08-18_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2022-08-18
Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1A_IW_GRDH_1SDV_20221017T234445_20221017T234510_045488_057066_CBA9
Exporting 22_2022-10-17_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2022-10-17
Number of images in collection:  2
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1A_IW_GRDH_1SDV_20220125T104728_20220125T104757_041616_04F352_C4A4
Exporting 23_2022-01-25_S1_GRD to oefa_img_v4_256_real
S1A_IW_GRDH_1SDV_20220125T104757_20220125T104819_041616_04F352_6EA6
Exporting 23_2022-01-25_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2022-01-25
Number of images in collection:  2
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1A_IW_GRDH_1SDV_20220125T104728_20220125T104757_041616_04F352_C4A4
Exporting 24_2022-01-25_S1_GRD to oefa_img_v4_256_real
S1A_IW_GRDH_1SDV_20220125T104757_20220125T104819_041616_04F352_6EA6
Exporting 24_2022-01-25_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2022-01-25
Number of images in collection:  1
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
S1A_IW_GRDH_1SDV_20220125T104757_20220125T104819_041616_04F352_6EA6
Exporting 25_2022-01-25_S1_GRD to oefa_img_v4_256_real
Processed data for event on 2022-01-25

In [ ]:
log_entries = []
for index, row in df.iterrows():
    start_date = pd.to_datetime(row['Fecha']) - timedelta(days=2)
    end_date = start_date + timedelta(days=5)
    roi
    log_entries.append({
        'file_name': f'{start_date.strftime("%Y%m%d")}_S1_GRD',
        'location': f'{ee.Geometry.Rectangle(json.loads(row["bbox"]))}',
        'time': start_date.strftime('%Y-%m-%d')
    })
print(log_entries)

[{'file_name': '20150519_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -80.1899209999998,\n              -6.6641417\n            ],\n            [\n              -80.1899209999998,\n              -6.9041417\n            ],\n            [\n              -79.94992099999979,\n              -6.9041417\n            ],\n            [\n              -79.94992099999979,\n              -6.6641417\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2015-05-19'}, {'file_name': '20160211_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -79.31877419999985,\n              -7.991677800000001\n            ],\n            [\n              -79.31877419999985,\n              -8.2316778\n            ],\n            [\n              -79.07877419999984,\n              -8.2316778\n            ],\n            [\n              -79.07877419999984,\n              -7.991677800000001\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2016-02-11'}, {'file_name': '20170709_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -81.5018334999999,\n              -4.4596872\n            ],\n            [\n              -81.5018334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.4596872\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2017-07-09'}, {'file_name': '20170709_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -81.5018334999999,\n              -4.4596872\n            ],\n            [\n              -81.5018334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.4596872\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2017-07-09'}, {'file_name': '20180330_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -77.37222979999993,\n              -11.708716800000001\n            ],\n            [\n              -77.37222979999993,\n              -11.9487168\n            ],\n            [\n              -77.13222979999992,\n              -11.9487168\n            ],\n            [\n              -77.13222979999992,\n              -11.708716800000001\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2018-03-30'}, {'file_name': '20180330_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -77.37222979999993,\n              -11.708716800000001\n            ],\n            [\n              -77.37222979999993,\n              -11.9487168\n            ],\n            [\n              -77.13222979999992,\n              -11.9487168\n            ],\n            [\n              -77.13222979999992,\n              -11.708716800000001\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2018-03-30'}, {'file_name': '20180330_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -77.37222979999993,\n              -11.708716800000001\n            ],\n            [\n              -77.37222979999993,\n              -11.9487168\n            ],\n            [\n              -77.13222979999992,\n              -11.9487168\n            ],\n            [\n              -77.13222979999992,\n              -11.708716800000001\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2018-03-30'}, {'file_name': '20180924_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -81.5018334999999,\n              -4.4596872\n            ],\n            [\n              -81.5018334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.4596872\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2018-09-24'}, {'file_name': '20180924_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -81.5018334999999,\n              -4.4596872\n            ],\n            [\n              -81.5018334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.4596872\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2018-09-24'}, {'file_name': '20181117_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -79.31877419999985,\n              -7.991677800000001\n            ],\n            [\n              -79.31877419999985,\n              -8.2316778\n            ],\n            [\n              -79.07877419999984,\n              -8.2316778\n            ],\n            [\n              -79.07877419999984,\n              -7.991677800000001\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2018-11-17'}, {'file_name': '20200316_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -81.5018334999999,\n              -4.4596872\n            ],\n            [\n              -81.5018334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.4596872\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2020-03-16'}, {'file_name': '20200316_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -81.5018334999999,\n              -4.4596872\n            ],\n            [\n              -81.5018334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.4596872\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2020-03-16'}, {'file_name': '20210119_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -81.5018334999999,\n              -4.4596872\n            ],\n            [\n              -81.5018334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.4596872\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2021-01-19'}, {'file_name': '20220113_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -77.37222979999993,\n              -11.708716800000001\n            ],\n            [\n              -77.37222979999993,\n              -11.9487168\n            ],\n            [\n              -77.13222979999992,\n              -11.9487168\n            ],\n            [\n              -77.13222979999992,\n              -11.708716800000001\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2022-01-13'}, {'file_name': '20220812_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -81.5018334999999,\n              -4.4596872\n            ],\n            [\n              -81.5018334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.4596872\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2022-08-12'}, {'file_name': '20221007_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -81.5018334999999,\n              -4.4596872\n            ],\n            [\n              -81.5018334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.6996872000000005\n            ],\n            [\n              -81.2618334999999,\n              -4.4596872\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2022-10-07'}, {'file_name': '20220113_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -77.38088499999994,\n              -11.681154000000001\n            ],\n            [\n              -77.38088499999994,\n              -11.921154\n            ],\n            [\n              -77.14088499999993,\n              -11.921154\n            ],\n            [\n              -77.14088499999993,\n              -11.681154000000001\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2022-01-13'}, {'file_name': '20220113_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -77.37133599999996,\n              -11.718696000000001\n            ],\n            [\n              -77.37133599999996,\n              -11.958696\n            ],\n            [\n              -77.13133599999995,\n              -11.958696\n            ],\n            [\n              -77.13133599999995,\n              -11.718696000000001\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2022-01-13'}, {'file_name': '20220113_S1_GRD', 'location': 'ee.Geometry({\n  "functionInvocationValue": {\n    "functionName": "GeometryConstructors.Polygon",\n    "arguments": {\n      "coordinates": {\n        "constantValue": [\n          [\n            [\n              -77.33610200000001,\n              -11.909534\n            ],\n            [\n              -77.33610200000001,\n              -12.149534\n            ],\n            [\n              -77.096102,\n              -12.149534\n            ],\n            [\n              -77.096102,\n              -11.909534\n            ]\n          ]\n        ]\n      },\n      "evenOdd": {\n        "constantValue": true\n      }\n    }\n  }\n})', 'time': '2022-01-13'}]

<ipython-input-21-4995214a4d0b>:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  start_date = pd.to_datetime(row['Fecha']) - timedelta(days=2)

In [ ]:
len(log_entries)

19

In [ ]:

parameter = {'START_DATE': '2018-01-01',
            'STOP_DATE': '2018-02-01',
            'POLARIZATION': 'VV',
            'ORBIT' : 'BOTH',
            'PLATFORM_NUMBER' : 'A',
            'ORBIT_NUM': None,
            'ROI': ee.Geometry.Rectangle([-47.1634, -3.00071, -45.92746, -5.43836]),
            'APPLY_BORDER_NOISE_CORRECTION': False,
            'APPLY_SPECKLE_FILTERING': True,
            'SPECKLE_FILTER_FRAMEWORK':'MONO',
            'SPECKLE_FILTER': 'LEE',
            'SPECKLE_FILTER_KERNEL_SIZE': 7,
            'SPECKLE_FILTER_NR_OF_IMAGES':10,
            'APPLY_TERRAIN_FLATTENING': True,
            'DEM': ee.Image('USGS/SRTMGL1_003'),
            'TERRAIN_FLATTENING_MODEL': 'VOLUME',
            'TERRAIN_FLATTENING_ADDITIONAL_LAYOVER_SHADOW_BUFFER':0,
            'FORMAT': 'DB',
            'CLIP_TO_ROI': True,
            'SAVE_ASSET': True
            }

    log_entries.append({
        'file_name': f'{start_date.strftime("%Y%m%d")}_S1_GRD',
        'location': f'{row["bbox_converted"]}',
        'time': start_date.strftime('%Y-%m-%d')
    })

wp.s1_preproc(parameter)

Number of images in collection:  13
Mono-temporal speckle filtering is completed
Radiometric terrain normalization is completed
Exporting S1A_IW_GRDH_1SDV_20180107T084137_20180107T084202_020046_022281_87D2 to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180107T084202_20180107T084227_020046_022281_1045 to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180107T084227_20180107T084252_020046_022281_EA84 to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180112T084946_20180112T085011_020119_0224E5_2A8F to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180112T085011_20180112T085036_020119_0224E5_EF72 to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180119T084137_20180119T084202_020221_02280E_5674 to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180119T084202_20180119T084227_020221_02280E_8D56 to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180119T084227_20180119T084252_020221_02280E_3A38 to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180124T084946_20180124T085011_020294_022A74_263C to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180124T085011_20180124T085036_020294_022A74_A2B5 to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180131T084136_20180131T084201_020396_022D9D_3924 to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180131T084201_20180131T084226_020396_022D9D_DFB2 to GEE_SAR_processed
Exporting S1A_IW_GRDH_1SDV_20180131T084226_20180131T084251_020396_022D9D_DE6D to GEE_SAR_processed

In [ ]:
task.status()

NameError: name 'task' is not defined

In [ ]:
first_image = s1_processed.first()
first_image

In [ ]:
# Fetch and print the image metadata
metadata = first_image.getInfo()
print(metadata)

{'type': 'Image', 'bands': [{'id': 'VV', 'data_type': {'type': 'PixelType', 'precision': 'double'}, 'dimensions': [28724, 22174], 'origin': [0, 1], 'crs': 'EPSG:32723', 'crs_transform': [10, 0, 330129.7609730883, 0, -10, 9738702.70357257]}, {'id': 'angle', 'data_type': {'type': 'PixelType', 'precision': 'float'}, 'dimensions': [21, 10], 'crs': 'EPSG:32723', 'crs_transform': [-12553.2307824397, -4308.04279434518, 617369.086477932, 2730.286116309464, -20051.85848106444, 9684077.970874848]}], 'properties': {'SLC_Processing_software_name': 'Sentinel-1 IPF', 'sliceProductFlag': 'true', 'S1TBX_Calibration_vers': '6.0.4', 'orbitNumber_start': 20046, 'GRD_Post_Processing_start': 1515322414640, 'sliceNumber': 2, 'GRD_Post_Processing_facility_site': 'Airbus DS-Newport', 'instrument': 'Synthetic Aperture Radar', 'GRD_Post_Processing_facility_name': 'Copernicus S1 Core Ground Segment - UPA', 'resolution': 'H', 'SLC_Processing_facility_name': 'Copernicus S1 Core Ground Segment - UPA', 'GRD_Post_Processing_software_name': 'Sentinel-1 IPF', 'familyName': 'SENTINEL-1', 'platform_number': 'A', 'S1TBX_SAR_Processing_vers': '6.0.4', 'segmentStartTime': 1515314469080, 'productType': 'GRD', 'missionDataTakeID': 139905, 'GRD_Post_Processing_facility_country': 'United Kingdom', 'nssdcIdentifier': '2014-016A', 'productClass': 'S', 'phaseIdentifier': 1, 'orbitProperties_ascendingNodeTime': 1515311481280, 'stopTimeANX': 3041494, 'orbitProperties_pass': 'DESCENDING', 'relativeOrbitNumber_stop': 24, 'productComposition': 'Slice', 'productClassDescription': 'SAR Standard L1 Product', 'SLC_Processing_facility_site': 'Airbus DS-Newport', 'GRD_Post_Processing_software_version': '002.84', 'GRD_Post_Processing_stop': 1515323047000, 'system:time_start': 1515314497000, 'SLC_Processing_software_version': '002.84', 'orbitNumber_stop': 20046, 'instrumentMode': 'IW', 'totalSlices': 12, 'instrumentConfigurationID': 6, 'SLC_Processing_stop': 1515322834000, 'startTimeANX': 3016496, 'SLC_Processing_start': 1515322520000, 'resolution_meters': 10, 'instrumentSwath': 'IW', 'relativeOrbitNumber_start': 24, 'productTimelinessCategory': 'Fast-24h', 'cycleNumber': 129, 'system:index': 'S1A_IW_GRDH_1SDV_20180107T084137_20180107T084202_020046_022281_87D2', 'SNAP_Graph_Processing_Framework_GPF_vers': '6.0.4', 'SLC_Processing_facility_org': 'ESA', 'SLC_Processing_facility_country': 'United Kingdom', 'GRD_Post_Processing_facility_org': 'ESA', 'transmitterReceiverPolarisation': ['VV', 'VH']}}

In [ ]:
# Print specific properties
acquisition_date = first_image.date().format().getInfo()
print("Acquisition Date:", acquisition_date)

# Example to fetch and print projection information
projection = first_image.select('VV').projection().getInfo()
print("Projection Information:", projection)

# Getting band information
band_info = first_image.bandNames().getInfo()
print("Band Names:", band_info)

Acquisition Date: 2018-01-07T08:41:37
Projection Information: {'type': 'Projection', 'crs': 'EPSG:32723', 'transform': [10, 0, 330129.7609730883, 0, -10, 9738702.70357257]}
Band Names: ['VV', 'angle']

In [ ]:
vv_band = first_image.select('VV')

In [ ]:
vv_band

In [ ]:
link = first_image.getDownloadURL({
    'scale': 352,
    'crs': 'EPSG:4326',
    'fileFormat': "GeoTIFF",
    'region': first_image.geometry().coordinates().getInfo()})
print(link)

EEException: Pixel grid dimensions (9699311x8154615) must be less than or equal to 32768.

In [ ]:
# Define a smaller region
smaller_region = ee.Geometry.Rectangle([-81.31, -4.63, -81.29, -4.61])

link = first_image.getDownloadURL({
    'scale': 10,
    'crs': 'EPSG:4326',
    'fileFormat': "GeoTIFF",
    'region': smaller_region.coordinates().getInfo()
})
print(link)

https://earthengine.googleapis.com/v1/projects/ee-cima/thumbnails/e8a13dba1b659f51705fc30f2f52a615-41f6cc96c6b6988f55dbcfe1c7aa6da0:getPixels

In [ ]:
link = first_image.getDownloadURL({
    'fileFormat': 'GeoTIFF',
    'region': first_image.geometry()})
print(link)

EEException: Total request size (1437868918 bytes) must be less than or equal to 50331648 bytes.

In [ ]:
manual_region = ee.Geometry.Rectangle([-81.3318335, -4.6396872, -81.2718335, -4.5196872])

In [ ]:
f_32 = first_image.toFloat()
task = ee.batch.Export.image.toDrive(image=f_32,
                                     description='elevation_near_lyon_france',
                                     scale=30,
                                     region=f_32.geometry(),
                                     folder='GEE_Folder',
                                     crs='EPSG:4326')
task.start()

In [ ]:
task.status()

{'state': 'COMPLETED',
 'description': 'elevation_near_lyon_france',
 'priority': 100,
 'creation_timestamp_ms': 1713747086415,
 'update_timestamp_ms': 1713747667333,
 'start_timestamp_ms': 1713747092456,
 'task_type': 'EXPORT_IMAGE',
 'destination_uris': ['https://drive.google.com/#folders/1gfzDvoYPs4fUUuvUNZkHdyon3GcrNplV'],
 'attempt': 1,
 'batch_eecu_usage_seconds': 8475.474609375,
 'id': '6MVBJMXQFULVXZ63X5WZFT7H',
 'name': 'projects/ee-cima/operations/6MVBJMXQFULVXZ63X5WZFT7H'}

In [ ]:
link = f_32.getDownloadURL({
    'crs': 'EPSG:4326',
    'fileFormat': 'GeoTIFF',
    'region': f_32.geometry()})
print(link)

https://earthengine.googleapis.com/v1/projects/ee-cima/thumbnails/f508d3d7e7fd11211763c65522990e59-8e52e5d22e9ee2e506517beefcc01db8:getPixels